<a href="https://colab.research.google.com/github/KWERA/Eulers_Loan_Prediction/blob/main/LOAN_FRAUD_DETECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')
import pandas as pd
df1 = pd.read_csv("/content/drive/MyDrive/data/traindemographics.csv")
df2 =pd.read_csv("/content/drive/MyDrive/data/trainperf.csv")
df3 =pd.read_csv("/content/drive/MyDrive/data/trainprevloans.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4346 entries, 0 to 4345
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4346 non-null   object
 1   birthdate                   4346 non-null   object
 2   bank_account_type           4346 non-null   object
 3   longitude_gps               4346 non-null   float64
 4   latitude_gps                4346 non-null   float64
 5   bank_name_clients           4346 non-null   object
 6   bank_branch_clients         51 non-null     object
 7   employment_status_clients   3698 non-null   object
 8   level_of_education_clients  587 non-null    object
dtypes: float64(2), object(7)
memory usage: 305.7+ KB

In [ ]:
df1.head(3)

In [ ]:
df1.tail(3)

In [18]:
df1.describe()

       longitude_gps  latitude_gps
count    4346.000000   4346.000000
mean        4.626189      7.251356
std         7.184832      3.055052
min      -118.247009    -33.868818
25%         3.354953      6.470610
50%         3.593302      6.621888
75%         6.545220      7.425052
max       151.209290     71.228069

In [20]:
df1.isnull()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...
4341,False,False,False,False,False,False,True,False,False
4342,False,False,False,False,False,False,True,True,True
4343,False,False,False,False,False,False,True,False,True
4344,False,False,False,False,False,False,False,False,False
4345,False,False,False,False,False,False,True,False,True

In [22]:
df1.notnull()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,True,True,True,True,True,True,False,False,False
1,True,True,True,True,True,True,False,True,False
2,True,True,True,True,True,True,False,False,False
3,True,True,True,True,True,True,False,True,False
4,True,True,True,True,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...
4341,True,True,True,True,True,True,False,True,True
4342,True,True,True,True,True,True,False,False,False
4343,True,True,True,True,True,True,False,True,False
4344,True,True,True,True,True,True,True,True,True
4345,True,True,True,True,True,True,False,True,False